name: kakao_map_sdk
description: "A Flutter plugin that provides Kakao Map."
version: 0.2.0-dev.5
repository: https://github.com/gunyu1019/flutter_kakao_maps
issue_tracker: https://github.com/gunyu1019/flutter_kakao_maps/issues?q=is%3Aissue%20state%3Aopen%20

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kr.yhs.flutter_kakao_maps
        pluginClass: FlutterKakaoMapsPlugin
      ios:
        pluginClass: FlutterKakaoMapsPlugin
