name: Verify Lint

on:
  workflow_dispatch
    
jobs:
  lint_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7.2
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.2
      - name: Install dependencies
        run: flutter pub get
      - name: Verify dart code for lint.
        run: |
          echo "KAKAO_API_KEY=1234" >> assets/config/.env
          flutter analyze
      - name: Verify dart code for formatting.
        run: |
          dart format ./lib --set-exit-if-changed
          dart format ./example/lib --set-exit-if-changed
  lint_swift:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SwiftFormat
        run: |
          /usr/bin/git clone https://github.com/nicklockwood/SwiftFormat.git swiftformat -b main
      - name: Verify swift code for lint with SwiftFormat.
        run: |
          swiftformat/CommandLineTool/swiftformat --lint ./ios --reporter github-actions-log
          swiftformat/CommandLineTool/swiftformat --lint ./example/ios --reporter github-actions-log
  lint_kotlin:
    env:
      ktkmt-version: 0.54
      code-style: google-style  # meta-style, google-style, kotlinlang-style
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 18 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Install ktkmt
        run: |
          wget https://repo1.maven.org/maven2/com/facebook/ktfmt/$KTFMT_VERSION/ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar
        env:
          KTFMT_VERSION: ${{ env.ktkmt-version }}
      - name : Verify kotlin code for lint with ktfmt
        run: |
          java -jar ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar ./android --$CODE_STYLE --set-exit-if-changed
          java -jar ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar ./example/android --$CODE_STYLE --set-exit-if-changed
        env:
          KTFMT_VERSION: ${{ env.ktkmt-version }}
          CODE_STYLE: ${{ env.code-style }}

