name: Review Formatting

on:
  pull_request: 
    branches: develop
    types: [opened, reopened, synchronize]
    
jobs:
  formatting_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7.2
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.2
      - name: Install dependencies
        run: flutter pub get
      - name: Formatting dart code
        run: |
          dart format ./lib
          dart format ./example/lib
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest
      - name: Writing review of dart part.
        run: |
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          reviewdog -f=diff -f.diff.strip=1 -name="Dart" -log-level="info" -reporter=github-pr-review < "${TMPFILE}"
        env: 
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
  formatting_swift:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SwiftFormat
        run: |
          /usr/bin/git clone https://github.com/nicklockwood/SwiftFormat.git swiftformat -b main
      - name: Verify swift code for lint with SwiftFormat.
        run: |
          TMP_REPORT_FILE=$(mktemp)
          swiftformat/CommandLineTool/swiftformat ./ios ./example/ios --lint --lenient --reporter xml --report "SWIFT_REPORT.xml"
          swiftformat/CommandLineTool/swiftformat ./ios ./example/ios    
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest
      - name: Writing review of swift part.
        run: |
          cat "SWIFT_REPORT.xml" | reviewdog -f=checkstyle -diff="git diff" -name="SwiftFormat" -log-level="info" -reporter=github-pr-review
        env: 
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
  formatting_kotlin:
    env:
      ktkmt-version: 0.54
      code-style: google-style  # meta-style, google-style, kotlinlang-style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 18 (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'
      - name: Install ktkmt
        run: |
          wget https://repo1.maven.org/maven2/com/facebook/ktfmt/$KTFMT_VERSION/ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar
        env:
          KTFMT_VERSION: ${{ env.ktkmt-version }}
      - name : Verify kotlin code for lint with ktfmt
        run: |
          java -jar ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar ./android --$CODE_STYLE
          java -jar ktfmt-$KTFMT_VERSION-jar-with-dependencies.jar ./example/android --$CODE_STYLE
        env:
          KTFMT_VERSION: ${{ env.ktkmt-version }}
          CODE_STYLE: ${{ env.code-style }}
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest
      - name: Writing review of kotlin part.
        run: |
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          reviewdog -f=diff -f.diff.strip=1 -name="ktfmt" -log-level="info" -reporter=github-pr-review < "${TMPFILE}"
        env: 
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
